app = "brokerbase"
primary_region = "bom"   # Mumbai, India

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  min_machines_running = 0

[vm]
  size = "shared-cpu-1x"
  memory = "256"